### ISSUE TITLE
Mob.iq older Mobilus product

### ISSUE THREAD

**Issue by ha5atp** [Tymec/pl.mobilus.mobiq#1]
Hello!

I have ten mobilus motors in my house (M53 MR10/14) but they are earlier than 2017 and unfortunately they only know the Cosmo protocol and not the Cosmo 2/Way. I would like to know if I can control it with Mob.iq through HomeyPro or is there another possible way for integration. 
When I put my motor in program mode, then the app cannot find the shutter motor. With Mob.iq now.

Thanks!

**Comment by Tymec** [comment]
Unfortunately this app only supports z-wave enabled Mob.iq motors.
